spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catalog
    username: jpauser # ?? ?? ???
    password: jpapassword # ?? ?? ????
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true