nexus:
  api:
    url: http://nexus:8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/appcatalog_db
    username: appcatalog_user # docker-compose.yml에 설정된 POSTGRES_USER와 동일
    password: appcatalog_password # docker-compose.yml에 설정된 POSTGRES_PASSWORD와 동일
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true